@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbeyJhdXRob3JpdHkiOiJST0xFX0FETUlOIn1dLCJpYXQiOjE3NTM2MTE4MTMsImV4cCI6MTc1MzY5ODIxM30.g54cnMSl0R5InUpkQBaVj-fkggKsTsHof4Zx8QV_AtI

###login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

###register artem
POST http://localhost:8080/admin/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "user",
  "password": "user"
}

###admin
GET http://localhost:8080/admin
Authorization: Bearer {{token}}
Content-Type: application/json

{

}

###users
GET http://localhost:8080/admin/users
Authorization: Bearer {{token}}
Content-Type: application/json

{

}

###user
GET http://localhost:8080/user
Authorization: Bearer {{token}}
Content-Type: application/json

{

}
