#@token = eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbeyJhdXRob3JpdHkiOiJST0xFX0FETUlOIn1dLCJpYXQiOjE3NTQxMjI4NjIsImV4cCI6MTc1NDIwOTI2Mn0.Z84_enHWsn6nGiF5MKhyAW-sAzDXPHNAKu1lPo7e4Sk

###login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

> {%
    client.global.set("token", response.body.token);
%}


###register artem
POST http://localhost:8080/admin/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "user",
  "password": "user",
  "email": "user@email.com"
}

###admin
GET http://localhost:8080/admin
Authorization: Bearer {{token}}
Content-Type: application/json

{

}

###users
GET http://localhost:8080/admin/users
Authorization: Bearer {{token}}
Content-Type: application/json

{

}

###user
GET http://localhost:8080/user
Authorization: Bearer {{token}}
Content-Type: application/json

{

}
